---
- name: Crear un directorio de prueba
  hosts: all
  #become: true
  tasks: 
    - name: Crear directorio
      file: 
        path: /tmp/ansible_check
        state: directory
        mode: '0755'
      register: resultado 

    - name: Mostrar mensaje de preuba  
      debug: 
        msg: "Esto es una prueba"
      when: resultado.changed