---
- name: Crear un usuario usando extra vars
  hosts: all
  become: yes
  tasks:
    - name: Crear usuario con variables
      user:
        name: "{{ usuario }}"
        home: "{{ directorio_home }}"
        state: present