#CLASE: TAREA5
---
- name: Crear un usuario usando variables locales
  hosts: all
  become_user: ansible
  vars: 
    usuario: "ansible_user"
    directorio_home: "/home/ansible_user"
  tasks:
    - name: Crear usuario con variables
      user:
        name: "{{ usuario }}"
        home: "{{ directorio_home }}"
        state: present