---
- name: Crear un usuario usando variables locales
  hosts: all
  become: yes
  vars_files:
    - ./2.variables.yml
  tasks:
    - name: Crear usuario con variables
      user:
        name: "{{ usuario }}"
        home: "{{ directorio_home }}"
        state: present