---
- name: Crear un usuario e instalar un paquete usando un group vars
  hosts: tareaclase5
  become: yes
  tasks:
    - name: Crear usuario con variables
      user:
        name: "{{ usuario }}"
        home: "{{ directorio_home }}"
        state: present
    - name: Instalar un paquete
      apt: 
        name: "{{ paquete }}"
        state: present