---
- name: Instalar paquete tree
  hosts: all
  tasks:
    - name: tree
      apt: 
        name: tree
        state: present
      become: true

    - name: Verificar instalacion tree  
      command: tree --version
