---
- name: Ejemplo de rescue y always
  hosts: all
  become: true

  tasks: 
    - block: 
        - name: Forzar un fallo intencional
          #command: /bin/false
          debug: 
            msg: "Todo OK Jose Luis."

      rescue: 
        - name: Ejecutar tarea de recuperacion
          debug: 
            msg: "Se ha producido un error, ejecutando recuperacion."

      always:
        - name: Esta tarea siempre se ejecuta
          debug:
            msg: "Esta tarea se ejecuta siempre."
    
    - name: sistema
      debug: 
        var: ansible_distribution
      tags: 
        - etiqueta
