---
- name: Instalar apache
  apt: 
    name: apache2
    state: present
    update_cache: yes

- name: Iniciar y habilitar el servicio Apache
  service: 
    name: apache2
    state: started
    enabled: yes
  notify: Reiniciar apache

