---
- name: Instalar apache
  apt: 
    name: apache2
    state: present
    update_cache: yes

- name: Iniciar y habilitar el servicio Apache
  service: 
    name: apache2
    state: started
    enabled: no
  notify: Reiniciar apache

- name: Crear un fichero
  file:
    path: /tmp/prueba.txt
    state: touch
  notify: Mostrar mensaje test prueba1
