---
- name: Playbook principal que incluye playbook del submódulo
  hosts: localhost
  tasks:
    - name: Tarea en el playbook principal
      debug:
        msg: "Este es el playbook principal"
    
    - name: Incluir tareas del submódulo (si es necesario)
      include_tasks: submodulos/awx-test/pruebaApt.yml