---
- name: Proyecto final sencillo
  hosts: all
  become: yes
  vars_files: 
    - variables.yml
  tasks:
# Crear usuario
    - name: 1. Crear usuarios 
      user:
        name: "{{ usuario }}"
        home: "{{ directorio_home }}"
        state: present

# Instalar paquetes
    - name: 2. Instalar un paquete
      apt: 
        name: "{{ paquete }}"
        state: present

#Comandos de mantenimiento
    - name: 3. Comandos de mantenimiento
      apt:
        update_cache: yes
